name: Question
description: Question Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter_native_splash: ^2.2.0
  flutter_launcher_icons: ^0.9.1
  flutter_spinkit: ^5.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: '#B21DF2'
  android: true
  ios: true
  web: false
  image: "assets/question.png"

flutter_icons:
  image_path: "assets/icon-question.png"
  ios: true
  android: "laucher_icon"
  remove_alpha_ios: true
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icon-question.png'

flutter:
  uses-material-design: true
  assets:
    - assets/icon-question.png
